upstream ekto_backend {
    zone ekto_backend 64k;

    resolver 127.0.0.11 valid=15s ipv6=off;
    resolver_timeout 3s;

    server your-go-ekto:8080 resolve;
    keepalive 16;
}

server {
    listen 80 default_server;
    server_name _;

    root /usr/share/nginx/html;
    index test.html;

    client_max_body_size 2m;

    proxy_http_version 1.1;
    proxy_connect_timeout 5s;

    proxy_set_header Connection "";
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

    location / {
        try_files $uri $uri/ =404;
    }

    location = /api/v1/entities {
        proxy_pass http://ekto_backend;

        client_max_body_size 50m;
        proxy_request_buffering off;
        proxy_next_upstream off;

        client_body_timeout 60s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;
    }

    location ^~ /api/ {
        proxy_pass http://ekto_backend;
    }

    location ~ /\. {
        deny all;
    }
}
